name: Sync master with upstream

on:
  schedule:
  - cron:  "0 */6 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "pokealarm/pokealarm"
        source_branch: "dev"
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN  }}
